#!/usr/bin/env python

#just trying to make a simple script - this will ask the question about dinner
print ( "hey there, what did you have for dinner?" )

#this will get the input from the user
dinner_answer = raw_input()

#this will output the answer and ask if it was good
print ( "oh really, you had " + dinner_answer + ", was it good?" )

#and now we should get an answer again into another var
like_answer = raw_input()

#do an if statement
if like_answer in ['y', 'Y', 'yes', 'Yes', 'YES']:
	print ( "glad you liked it" )

